/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminiServizioRouteImport } from './routes/termini-servizio'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as CalcolatoreRouteImport } from './routes/calcolatore'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as IndexRouteImport } from './routes/index'

const TerminiServizioRoute = TerminiServizioRouteImport.update({
  id: '/termini-servizio',
  path: '/termini-servizio',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcolatoreRoute = CalcolatoreRouteImport.update({
  id: '/calcolatore',
  path: '/calcolatore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/calcolatore': typeof CalcolatoreRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy': typeof PrivacyRoute
  '/roi': typeof RoiRoute
  '/termini': typeof TerminiRoute
  '/termini-servizio': typeof TerminiServizioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/calcolatore': typeof CalcolatoreRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy': typeof PrivacyRoute
  '/roi': typeof RoiRoute
  '/termini': typeof TerminiRoute
  '/termini-servizio': typeof TerminiServizioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/calcolatore': typeof CalcolatoreRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy': typeof PrivacyRoute
  '/roi': typeof RoiRoute
  '/termini': typeof TerminiRoute
  '/termini-servizio': typeof TerminiServizioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/calcolatore'
    | '/cookie-policy'
    | '/privacy'
    | '/roi'
    | '/termini'
    | '/termini-servizio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/calcolatore'
    | '/cookie-policy'
    | '/privacy'
    | '/roi'
    | '/termini'
    | '/termini-servizio'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/calcolatore'
    | '/cookie-policy'
    | '/privacy'
    | '/roi'
    | '/termini'
    | '/termini-servizio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  CalcolatoreRoute: typeof CalcolatoreRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  RoiRoute: typeof RoiRoute
  TerminiRoute: typeof TerminiRoute
  TerminiServizioRoute: typeof TerminiServizioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termini-servizio': {
      id: '/termini-servizio'
      path: '/termini-servizio'
      fullPath: '/termini-servizio'
      preLoaderRoute: typeof TerminiServizioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcolatore': {
      id: '/calcolatore'
      path: '/calcolatore'
      fullPath: '/calcolatore'
      preLoaderRoute: typeof CalcolatoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  CalcolatoreRoute: CalcolatoreRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  PrivacyRoute: PrivacyRoute,
  RoiRoute: RoiRoute,
  TerminiRoute: TerminiRoute,
  TerminiServizioRoute: TerminiServizioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
